In [2]:
# installing numpy

!pip install numpy


In [4]:
# upgrading the numpy

!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\i501181\appdata\local\continuum\anaconda3\lib\site-packages (1.17.4)


In [5]:
# import numpy library using import command
import numpy as np # np is alias name

a=np.array([1,3]) # array with 1 row & 3 columns
a


array([1, 3])

In [6]:
type(a)

numpy.ndarray

In [33]:
# converting list to numpy.array
lst=[2,4,6]
ary_lst=np.array(lst)
ary_lst



array([2, 4, 6])

In [11]:
print(lst)

[2, 4, 6]


In [31]:
type(ary_lst)

numpy.ndarray

In [14]:
#zeros array

ary_zero=np.zeros((2,4))
ary_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#ones array
ary_one=np.ones((3,5))
ary_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
# removing decimals in the array values

ary_one=np.ones((2,3),dtype=np.int)
ary_one

array([[1, 1, 1],
       [1, 1, 1]])

In [57]:
# giving single value to array..By defaul it is taking as column count as below
ary_one=np.ones(3)
ary_one

array([1., 1., 1.])

In [76]:
ary_one=np.ones((1),dtype=np.int)
ary_one

array([1])

In [75]:
ary_one=2.3
ary_one

2.3